[package]
name = "helloworld-cargo"
version = "0.1.0"
authors = ["Kuber aaganja <kuber@gurzu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
